# fpath=(~/dotfiles/zsh/completion $fpath)

# get auto completes going
autoload -U compinit
compinit

bindkey '^I' complete-word # complete on tab, leave expansion to _expand

TZ="Europe/London"
HISTFILE=$HOME/.zhistory
HISTSIZE=20000
SAVEHIST=20000
setopt HIST_IGNORE_SPACE
HOSTNAME="`hostname`"
PAGER='less'

#LANGUAGE
LC_ALL='en_US.UTF-8'

GIT_MERGE_AUTOEDIT=no
export GIT_MERGE_AUTOEDIT

export EDITOR='nvim'

# But still use emacs-style zsh bindings
bindkey -e

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# AutoEnv
export AUTOENV_FILE_ENTER='.env'

# Antigen 
source $HOME/antigen.zsh
antigen bundle Tarrasch/zsh-autoenv
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle robbyrussell/oh-my-zsh plugins/z
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure
antigen apply


# NVM
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# z plugin gets aliased to 'j'
alias j="z"

# so autoenv runs all the time even when you open a tmux split
cd .

# source ZSH
source $HOME/dotfiles/zsh/aliases
source $HOME/dotfiles/zsh/functions
# source $HOME/dotfiles/zsh/prompt

autoload -U promptinit; promptinit
prompt pure

# Put things in ~/.bin into my $PATH
export PATH="./bin:$PATH"


case 'uname' in
    Darwin)
        # Mac things
    ;;
esac

